// Orchestra knowledge base. Years are approximate recording periods.
// Name matching (all normalised: lowercase, no accents, no apostrophes, whole words):
//   aliases        – tags and folder names; in file names only as a whole " - " part or a full name
//   artistAliases  – artist/conductor tags only (too ambiguous elsewhere)
//   nicknames      – tags and folder names only, never file names (they double as tango titles)
// "Surname, First" and "F. Surname" forms, and near-miss spellings, are derived in library.js.

export const ORCHESTRAS = [
  {
    id: 'darienzo', name: "Juan D'Arienzo", nickname: 'El Rey del Compás',
    aliases: ['juan darienzo', 'darienzo', 'd arienzo'], artistAliases: [], nicknames: [],
    active: [1928, 1975], color: '#d1495b',
    summary: 'Relentless, driving 2/4 beat with sharp staccato attacks. Made for dancing, and the music that brought the milongas back to life in 1935.',
    listenFor: [
      'Hard, clipped staccato on every beat. The rhythm never lets up.',
      'Violins playing short, biting notes rather than long phrases.',
      'Bandoneón variaciones (fast running passages) near the end.',
      '1935–38: Rodolfo Biagi\'s piano adds sparkling, cheeky fills between phrases.',
      '1950s+: bigger and more bombastic, with brassy accents and very fast tempos.',
    ],
    eras: [
      { years: '1935–1938', note: 'The "Biagi era": light, sprightly, piano fills. Singers Walter Cabral, Enrique Carbel.' },
      { years: '1938–1944', note: 'Alberto Echagüe (1938–39), then Alberto Reynal, Juan Carlos Lamas and Héctor Mauré (smooth, dark voice).' },
      { years: '1944–1975', note: 'Echagüe returns, plus Armando Laborde, Jorge Valdez and Mario Bustos. Faster and more theatrical.' },
    ],
    singers: ['Walter Cabral', 'Enrique Carbel', 'Alberto Echagüe', 'Alberto Reynal', 'Juan Carlos Lamas', 'Héctor Mauré', 'Armando Laborde', 'Jorge Valdez', 'Mario Bustos'],
    confusable: ['biagi', 'tanturi', 'varela', 'rodriguez'],
    vs: {
      biagi: 'Both are staccato, but D\'Arienzo is heavier and relentless, with violins leading. Biagi is lighter and quirkier, with syncopated piano jabs that seem to fall "off" the beat.',
      tanturi: 'Tanturi is just as rhythmic but rounder and less aggressive, and the singer sits more in the foreground.',
      varela: 'Varela (a D\'Arienzo alumnus) keeps the drive but adds lusher, more romantic 1950s strings.',
    },
    tracks: ['La cumparsita', 'Paciencia', 'Nada más', 'La puñalada (milonga)', 'El flete'],
  },
  {
    id: 'biagi', name: 'Rodolfo Biagi', nickname: 'Manos Brujas',
    aliases: ['rodolfo biagi', 'biagi'], artistAliases: [], nicknames: [],
    active: [1938, 1962], color: '#edae49',
    summary: 'Started his own orchestra after leaving D\'Arienzo. Playful, angular staccato built around the leader\'s piano.',
    listenFor: [
      'The piano "jabs": short, syncopated chords that land just off the beat.',
      'Choppy, teasing phrasing with sudden stops.',
      'A thinner, lighter texture than D\'Arienzo.',
      'Valses that skip and sparkle (Lágrimas y sonrisas).',
    ],
    eras: [
      { years: '1938–1942', note: 'Teófilo Ibáñez, Andrés Falgás, then Jorge Ortiz. The classic dance period.' },
      { years: '1942–1950s', note: 'Alberto Amor, Carlos Acuña, Carlos Heredia, Hugo Duval.' },
    ],
    singers: ['Teófilo Ibáñez', 'Andrés Falgás', 'Jorge Ortiz', 'Alberto Amor', 'Carlos Acuña', 'Carlos Heredia', 'Hugo Duval'],
    confusable: ['darienzo', 'tanturi', 'donato'],
    vs: {
      darienzo: 'Listen to the piano. If it constantly interjects with off-beat jabs and the band feels "spiky", it\'s Biagi.',
    },
    tracks: ['Lágrimas y sonrisas (vals)', 'Indiferencia', 'Gólgota'],
  },
  {
    id: 'disarli', name: 'Carlos Di Sarli', nickname: 'El Señor del Tango',
    aliases: ['carlos di sarli', 'di sarli', 'disarli'], artistAliases: [], nicknames: [],
    active: [1928, 1958], color: '#00798c',
    summary: 'Elegant and majestic. A steady, walking beat under lush, singing violins, with the leader\'s distinctive piano holding it all together.',
    listenFor: [
      'A clear, unhurried pulse with a steady walking feel.',
      'A full, legato violin section carrying the melody.',
      'Bandoneóns used mainly for rhythm, with few flashy solos.',
      'Di Sarli\'s piano: bell-like single notes and bass "chimes" that link phrases.',
    ],
    eras: [
      { years: '1939–1944', note: 'Roberto Rufino. Brighter, bouncier and more rhythmic than the later Di Sarli.' },
      { years: '1944–1948', note: 'Alberto Podestá, Jorge Durán. Smoother and more romantic.' },
      { years: '1951–1958', note: 'Grand instrumentals (Bahía Blanca, Don Juan), plus Oscar Serpa, Mario Pomar and Roberto Florio. Very lush and slow.' },
    ],
    singers: ['Roberto Rufino', 'Alberto Podestá', 'Jorge Durán', 'Oscar Serpa', 'Mario Pomar', 'Roberto Florio', 'Argentino Ledesma'],
    confusable: ['fresedo', 'calo', 'sassone', 'deangelis'],
    vs: {
      fresedo: 'Fresedo is sweeter and lighter on its feet (harp, vibraphone, delicate ornaments). Di Sarli is weightier, with a firmer beat.',
      calo: 'Caló gives the bandoneóns more of the spotlight and its piano is sparklier. Di Sarli\'s piano works low in the bass and the violins dominate.',
      sassone: 'Sassone borrowed the 1950s Di Sarli sound but is more symphonic and sentimental, with a less rigid beat.',
    },
    tracks: ['Bahía Blanca', 'Don Juan', 'A la gran muñeca', 'Organito de la tarde', 'Corazón'],
  },
  {
    id: 'troilo', name: 'Aníbal Troilo', nickname: 'Pichuco',
    aliases: ['anibal troilo', 'troilo'], artistAliases: [], nicknames: ['pichuco'],
    active: [1938, 1971], color: '#30638e',
    summary: 'Sophisticated arrangements that balance rhythm and lyricism. Troilo\'s own bandoneón breathes and pauses like a singer.',
    listenFor: [
      'Rich, intricate arrangements with contrasting sections.',
      'Expressive bandoneón solos with dramatic pauses and rubato.',
      'Strong forward swing in the 1941–44 recordings.',
      'Later work grows more concert-like and less danceable.',
    ],
    eras: [
      { years: '1941–1944', note: 'Francisco Fiorentino. Peak dance period: rhythmic and full of swing.' },
      { years: '1943–1950', note: 'Alberto Marino, Floreal Ruiz, Edmundo Rivero. More lyrical and complex.' },
      { years: '1950s–60s', note: 'Jorge Casal, Raúl Berón, Roberto Goyeneche. More for listening.' },
    ],
    singers: ['Francisco Fiorentino', 'Alberto Marino', 'Floreal Ruiz', 'Edmundo Rivero', 'Jorge Casal', 'Raúl Berón', 'Roberto Goyeneche'],
    confusable: ['pugliese', 'calo', 'laurenz', 'gobbi'],
    vs: {
      pugliese: 'Pugliese hits harder on beats 1 and 3 with a rasping "yumba" drag and wilder dynamics. Troilo is smoother and swings.',
      laurenz: 'Both are bandoneón-led. Laurenz is more percussive and virtuosic, while Troilo is more lyrical and arranged.',
    },
    tracks: ['Toda mi vida', 'Tinta roja', "Pa' que bailen los muchachos", 'Quejas de bandoneón', 'Sur'],
  },
  {
    id: 'pugliese', name: 'Osvaldo Pugliese', nickname: 'San Pugliese',
    aliases: ['osvaldo pugliese', 'pugliese'], artistAliases: [], nicknames: [],
    active: [1943, 1989], color: '#6a4c93',
    summary: 'Dramatic and deep: heavy marcato on 1 and 3 ("la yumba"), huge dynamic swings and tempo shifts.',
    listenFor: [
      'The "yumba": a heavy, dragging, almost growled accent on the strong beats.',
      'Sudden contrasts between thunderous passages and near-silence.',
      'Tempo that stretches and pushes (rubato), with long pauses.',
      'Soaring solo violin and solo bandoneón passages.',
    ],
    eras: [
      { years: '1943–1948', note: 'Roberto Chanel, Alberto Morán. The most danceable Pugliese.' },
      { years: '1948–1959', note: 'Morán, then Jorge Maciel and Miguel Montero. Increasingly dramatic.' },
      { years: '1960s+', note: 'Highly orchestral and theatrical (Gallo ciego, La yumba re-recordings).' },
    ],
    singers: ['Roberto Chanel', 'Alberto Morán', 'Jorge Maciel', 'Miguel Montero', 'Juan Carlos Cobos', 'Alfredo Belusi'],
    confusable: ['troilo', 'gobbi', 'laurenz'],
    vs: {
      troilo: 'If the accents feel heavy and "scraped", and the music suddenly drops to a whisper, it\'s Pugliese.',
    },
    tracks: ['Recuerdo', 'La yumba', 'Negracha', 'Gallo ciego', 'Emancipación'],
  },
  {
    id: 'calo', name: 'Miguel Caló', nickname: 'La orquesta de las estrellas',
    aliases: ['miguel calo'], artistAliases: ['calo'], nicknames: [],
    active: [1932, 1972], color: '#2e8b57',
    summary: 'Smooth, romantic and singer-centred, but still steady to dance to. Osmar Maderna\'s delicate piano adds sparkle.',
    listenFor: [
      'A warm, rounded, legato sound with a steady but gentle beat.',
      'Bright, filigree piano runs (Maderna).',
      'Beautiful voices up front (Berón, Podestá, Iriarte).',
      'Bandoneón section phrasing the melody smoothly.',
    ],
    eras: [
      { years: '1941–1943', note: 'Raúl Berón and Alberto Podestá. The classic "stars" period.' },
      { years: '1943–1950s', note: 'Raúl Iriarte, Luis Tolosa. Sweeter and more lyrical.' },
    ],
    singers: ['Raúl Berón', 'Alberto Podestá', 'Raúl Iriarte', 'Luis Tolosa'],
    confusable: ['disarli', 'demare', 'dagostino', 'troilo'],
    vs: {
      disarli: 'Caló has more bandoneón and a sparkly upper-register piano. Di Sarli is violin-dominated with bass-register piano.',
      demare: 'Demare is more melancholic and piano-led, with a softer pulse. Caló is more evenly balanced across the band.',
    },
    tracks: ['Al compás del corazón', 'Lejos de Buenos Aires'],
  },
  {
    id: 'tanturi', name: 'Ricardo Tanturi', nickname: 'Los Indios',
    aliases: ['ricardo tanturi', 'tanturi'], artistAliases: [], nicknames: ['los indios'],
    active: [1937, 1960], color: '#c75000',
    summary: 'Bright, clean and rhythmic with clear structure, and among the most reliably danceable music of the 1940s.',
    listenFor: [
      'A crisp, bouncy beat that\'s firm but rounder than D\'Arienzo.',
      'Simple, clear arrangements with the singer well forward.',
      'Alberto Castillo\'s brash, nasal, extrovert voice, or Enrique Campos\'s smooth, gentle one.',
    ],
    eras: [
      { years: '1940–1943', note: 'Alberto Castillo: cheerful and swaggering.' },
      { years: '1943–1946', note: 'Enrique Campos: smoother and more lyrical, but just as rhythmic.' },
    ],
    singers: ['Alberto Castillo', 'Enrique Campos', 'Roberto Videla'],
    confusable: ['darienzo', 'biagi', 'rodriguez', 'malerba'],
    vs: {
      darienzo: 'Tanturi grooves where D\'Arienzo hammers, and the voice matters more.',
    },
    tracks: ['Así se baila el tango', 'Una emoción', 'Oigo tu voz'],
  },
  {
    id: 'dagostino', name: "Ángel D'Agostino", nickname: 'Los dos Ángeles (with Vargas)',
    aliases: ['angel dagostino', 'dagostino', 'd agostino'], artistAliases: [], nicknames: [],
    active: [1940, 1963], color: '#8d6a9f',
    summary: 'Unpretentious, sweet and swinging. Sparse piano, a relaxed tempo, and the conversational voice of Ángel Vargas.',
    listenFor: [
      'A relaxed, light pulse that never rushes.',
      'Sparse, elegant piano fills from D\'Agostino.',
      'Ángel Vargas: an intimate, almost spoken delivery.',
      'An uncluttered, transparent texture.',
    ],
    eras: [
      { years: '1940–1946', note: 'Ángel Vargas. Almost the entire essential catalogue.' },
      { years: '1946+', note: 'Tino García, Ricardo Ruiz, and the spoken Café Domínguez (1955).' },
    ],
    singers: ['Ángel Vargas', 'Tino García', 'Ricardo Ruiz'],
    confusable: ['calo', 'donato', 'otv', 'demare'],
    vs: {
      calo: 'D\'Agostino is lighter and more laid-back, with less lush strings and a more playful piano.',
    },
    tracks: ['Tres esquinas', 'Café Domínguez', 'Muchachos comienza la ronda'],
  },
  {
    id: 'fresedo', name: 'Osvaldo Fresedo', nickname: 'El Pibe de La Paternal',
    aliases: ['osvaldo fresedo', 'fresedo'], artistAliases: [], nicknames: [],
    active: [1925, 1980], color: '#4f9d9d',
    summary: 'Refined and sweet: soft dynamics, ornate textures, and unusual colours like harp and vibraphone.',
    listenFor: [
      'A soft, velvety sound with no harsh accents.',
      'Harp glissandi and vibraphone notes (from the late 1930s).',
      'Light, lilting rhythm and elegant ornaments.',
      'Roberto Ray\'s high, polished tenor in the 1930s.',
    ],
    eras: [
      { years: '1933–1939', note: 'Roberto Ray: high tenor, very romantic.' },
      { years: '1939–1950s', note: 'Ricardo Ruiz, Oscar Serpa, Héctor Pacheco. Lush and silky.' },
    ],
    singers: ['Roberto Ray', 'Ricardo Ruiz', 'Oscar Serpa', 'Héctor Pacheco'],
    confusable: ['disarli', 'deangelis', 'sassone'],
    vs: {
      disarli: 'Fresedo floats. Di Sarli walks with weight. Listen for harp and vibraphone (Fresedo).',
    },
    tracks: ['Vida mía', 'Buscándote', 'Pampero', 'El once'],
  },
  {
    id: 'canaro', name: 'Francisco Canaro', nickname: 'Pirincho',
    aliases: ['francisco canaro', 'canaro'], artistAliases: [], nicknames: ['pirincho'],
    active: [1915, 1964], color: '#b5651d',
    summary: 'Enormous output with simple, steady, very danceable arrangements. Canaro is the king of the classic milonga and of cheerful valses.',
    listenFor: [
      'A straightforward, even beat and uncomplicated arrangements.',
      'An "old-fashioned" 1930s sound, often with a refrain singer (estribillista).',
      'Very characteristic milongas: bouncy, light and clear.',
    ],
    eras: [
      { years: '1927–1934', note: 'Charlo, Ernesto Famá. The old guard / early golden age.' },
      { years: '1935–1940', note: 'Roberto Maida, Francisco Amor. Smooth and popular.' },
      { years: '1940s–50s', note: 'Carlos Roldán, Eduardo Adrián, Alberto Arenas.' },
    ],
    singers: ['Charlo', 'Ernesto Famá', 'Roberto Maida', 'Francisco Amor', 'Carlos Roldán', 'Eduardo Adrián'],
    confusable: ['lomuto', 'firpo', 'donato', 'otv'],
    vs: {
      lomuto: 'Very similar era and feel. Lomuto is slightly more stiff and martial, while Canaro is rounder and more "sung".',
    },
    tracks: ['Poema', 'Milonga sentimental', 'Reliquias porteñas', 'Corazón de oro (vals)'],
  },
  {
    id: 'donato', name: 'Edgardo Donato', nickname: '',
    aliases: ['edgardo donato'], artistAliases: [], nicknames: [],
    active: [1932, 1958], color: '#e07a5f',
    summary: 'Joyful, bouncy and a bit eccentric. Playful rhythms, sudden accents, and lots of charming valses and milongas.',
    listenFor: [
      'A cheeky, bouncing rhythm with humorous touches.',
      'Light vocals, often in duets or trios (Lagos, Morales, Gavio).',
      'Quirky surprises: sudden accents, stops and tempo play.',
    ],
    eras: [
      { years: '1932–1945', note: 'Horacio Lagos, Lita Morales, Romeo Gavio. The essential recordings.' },
    ],
    singers: ['Horacio Lagos', 'Lita Morales', 'Romeo Gavio'],
    confusable: ['rodriguez', 'biagi', 'canaro'],
    vs: {
      rodriguez: 'Both are cheerful. Donato is quirkier and more surprising, while Rodríguez is smoother and more even.',
    },
    tracks: ['A media luz', 'El huracán'],
  },
  {
    id: 'rodriguez', name: 'Enrique Rodríguez', nickname: 'La orquesta de todos los ritmos',
    aliases: ['enrique rodriguez'], artistAliases: [], nicknames: [],
    active: [1936, 1971], color: '#81b29a',
    summary: 'Cheerful, clean and easygoing. Also played foxtrots and pasodobles, and his valses and tangos have a light, bouncing step.',
    listenFor: [
      'A light, even, bouncy beat. Friendly rather than fiery.',
      'Armando Moreno\'s warm, clear voice.',
      'Simple, transparent arrangements.',
    ],
    eras: [
      { years: '1937–1945', note: 'Roberto Flores, then Armando Moreno. The classic sound.' },
    ],
    singers: ['Roberto Flores', 'Armando Moreno'],
    confusable: ['donato', 'tanturi', 'malerba', 'darienzo'],
    vs: {},
    tracks: ['Llorar por una mujer', 'Tengo mil novias', 'Salud, dinero y amor (vals)'],
  },
  {
    id: 'laurenz', name: 'Pedro Laurenz', nickname: '',
    aliases: ['pedro laurenz', 'laurenz'], artistAliases: [], nicknames: [],
    active: [1937, 1960], color: '#3d405b',
    summary: 'A virtuoso bandoneonist\'s orchestra: powerful, rhythmic and intense, with brilliant bandoneón passages.',
    listenFor: [
      'A dense, percussive bandoneón section.',
      'Virtuoso bandoneón runs and variations.',
      'Vigorous, slightly rough-edged drive.',
    ],
    eras: [
      { years: '1937–1944', note: 'Juan Carlos Casas, Martín Podestá, Alberto Podestá.' },
    ],
    singers: ['Juan Carlos Casas', 'Martín Podestá', 'Alberto Podestá'],
    confusable: ['troilo', 'pugliese', 'darienzo'],
    vs: {
      troilo: 'Laurenz is more percussive and virtuosic, while Troilo is more lyrical, with more pauses and arranging.',
    },
    tracks: ['Milonga de mis amores', 'Amurado'],
  },
  {
    id: 'demare', name: 'Lucio Demare', nickname: '',
    aliases: ['lucio demare', 'demare'], artistAliases: [], nicknames: [],
    active: [1938, 1960], color: '#577590',
    summary: 'Lyrical and melancholic, centred on Demare\'s expressive piano. Soft-edged and romantic.',
    listenFor: [
      'A prominent, singing piano.',
      'A gentle, soft pulse and a bittersweet mood.',
      'Romantic vocals (Juan Carlos Miranda, Raúl Berón).',
    ],
    eras: [
      { years: '1942–1944', note: 'Juan Carlos Miranda, Raúl Berón, Horacio Quintana. The classic recordings.' },
    ],
    singers: ['Juan Carlos Miranda', 'Raúl Berón', 'Horacio Quintana'],
    confusable: ['calo', 'dagostino'],
    vs: {
      calo: 'Demare is more piano-driven and wistful. Caló has a fuller section sound.',
    },
    tracks: ['Malena', 'Mañanitas de Montmartre'],
  },
  {
    id: 'deangelis', name: 'Alfredo De Angelis', nickname: 'El Colorado de Banfield',
    aliases: ['alfredo de angelis', 'de angelis', 'deangelis'], artistAliases: [], nicknames: [],
    active: [1943, 1977], color: '#f28482',
    summary: 'Popular, polished and pleasant. Steady rhythm, decorative piano, and famous vocal duets.',
    listenFor: [
      'A steady, moderate tempo that\'s easy to follow.',
      'Ornamental piano flourishes.',
      'The Carlos Dante & Julio Martel duets, especially in valses.',
    ],
    eras: [
      { years: '1943–1951', note: 'Julio Martel, Carlos Dante (and their duets).' },
      { years: '1950s+', note: 'Oscar Larroca, Juan Carlos Godoy.' },
    ],
    singers: ['Carlos Dante', 'Julio Martel', 'Oscar Larroca', 'Juan Carlos Godoy'],
    confusable: ['disarli', 'fresedo', 'calo'],
    vs: {},
    tracks: ['Pregonera (vals)', 'El pollito'],
  },
  {
    id: 'lomuto', name: 'Francisco Lomuto', nickname: '',
    aliases: ['francisco lomuto', 'lomuto'], artistAliases: [], nicknames: [],
    active: [1922, 1950], color: '#a26769',
    summary: 'A 1930s classic: firm, square rhythm and a martial, straightforward style.',
    listenFor: ['A square, march-like beat.', 'Plain, old-school arrangements.', 'Fernando Díaz or Jorge Omar on vocals.'],
    eras: [{ years: '1930s', note: 'Fernando Díaz, Jorge Omar, Alberto Rivera.' }],
    singers: ['Fernando Díaz', 'Jorge Omar', 'Alberto Rivera'],
    confusable: ['canaro', 'firpo', 'otv'],
    vs: {},
    tracks: [],
  },
  {
    id: 'firpo', name: 'Roberto Firpo', nickname: '',
    aliases: ['roberto firpo', 'firpo'], artistAliases: [], nicknames: [],
    active: [1910, 1959], color: '#8a817c',
    summary: 'Old guard (guardia vieja) pioneer. Simple, often instrumental pieces with an early-20th-century feel, from orchestra or quartet.',
    listenFor: ['A "vintage" recording sound.', 'Simple melody plus accompaniment.', 'Often a small group (Cuarteto Firpo).'],
    eras: [{ years: '1910s–1940s', note: 'Mostly instrumental.' }],
    singers: [],
    confusable: ['canaro', 'lomuto', 'decaro'],
    vs: {},
    tracks: ['El amanecer'],
  },
  {
    id: 'decaro', name: 'Julio De Caro', nickname: '',
    aliases: ['julio de caro', 'de caro', 'decaro'], artistAliases: [], nicknames: [],
    active: [1924, 1953], color: '#9c6644',
    summary: 'The guardia nueva innovator of the 1920s, with complex counterpoint and an expressive violin (sometimes the horned Stroh violin).',
    listenFor: ['Intricate counterpoint for the 1920s.', 'Expressive, sometimes nasal-sounding violin.', 'An older recording quality.'],
    eras: [{ years: '1924–1932', note: 'The influential sextet.' }],
    singers: [],
    confusable: ['firpo', 'canaro'],
    vs: {},
    tracks: ['Boedo', 'El monito', 'Mala junta'],
  },
  {
    id: 'otv', name: 'Orquesta Típica Victor', nickname: 'OTV',
    aliases: ['orquesta tipica victor', 'tipica victor'], artistAliases: ['otv'], nicknames: [],
    active: [1925, 1944], color: '#6d597a',
    summary: 'The Victor record label\'s house orchestra. Polished, clean and versatile, with many different directors and singers.',
    listenFor: ['A neat, studio-polished sound.', 'A balanced, conservative style.', '1930s valses and milongas.'],
    eras: [{ years: '1925–1944', note: 'Rotating singers including Ángel Vargas.' }],
    singers: ['Ángel Vargas'],
    confusable: ['canaro', 'lomuto', 'dagostino'],
    vs: {},
    tracks: [],
  },
  {
    id: 'varela', name: 'Héctor Varela', nickname: '',
    aliases: ['hector varela', 'varela'], artistAliases: [], nicknames: [],
    active: [1950, 1980], color: '#bc4749',
    summary: 'A 1950s orchestra from a former D\'Arienzo bandoneonist, mixing a driving beat with romantic strings and popular singers.',
    listenFor: ['D\'Arienzo-like drive but with lusher strings.', 'Big 1950s vocals.'],
    eras: [{ years: '1950s', note: 'Argentino Ledesma, Rodolfo Lesica.' }],
    singers: ['Argentino Ledesma', 'Rodolfo Lesica'],
    confusable: ['darienzo', 'deangelis'],
    vs: {},
    tracks: [],
  },
  {
    id: 'malerba', name: 'Ricardo Malerba', nickname: '',
    aliases: ['ricardo malerba', 'malerba'], artistAliases: [], nicknames: [],
    active: [1941, 1958], color: '#90be6d',
    summary: 'Light, cheerful and uncomplicated 1940s dance music.',
    listenFor: ['A light, bright, bouncy beat.', 'Orlando Medina\'s clean voice.'],
    eras: [{ years: '1940s', note: 'Orlando Medina.' }],
    singers: ['Orlando Medina'],
    confusable: ['rodriguez', 'tanturi'],
    vs: {},
    tracks: [],
  },
  {
    id: 'federico', name: 'Domingo Federico', nickname: '',
    aliases: ['domingo federico'], artistAliases: [], nicknames: [],
    active: [1943, 1960], color: '#43aa8b',
    summary: 'A bandoneonist-led 1940s orchestra: melodic and rhythmic, with Carlos Vidal\'s warm voice.',
    listenFor: ['A rounded, melodic bandoneón lead.', 'Carlos Vidal\'s vocals.'],
    eras: [{ years: '1940s', note: 'Carlos Vidal.' }],
    singers: ['Carlos Vidal'],
    confusable: ['calo', 'troilo'],
    vs: {},
    tracks: ['Yo soy el tango'],
  },
  {
    id: 'sassone', name: 'Florindo Sassone', nickname: '',
    aliases: ['florindo sassone', 'sassone'], artistAliases: [], nicknames: [],
    active: [1947, 1980], color: '#277da1',
    summary: 'A 1950s–60s sound strongly inspired by late Di Sarli: lush, symphonic and sentimental.',
    listenFor: ['A sweeping string section.', 'Di Sarli-like piano gestures, but softer and more romantic.'],
    eras: [{ years: '1950s–60s', note: 'Mostly instrumental for the dance floor.' }],
    singers: [],
    confusable: ['disarli', 'fresedo'],
    vs: {},
    tracks: [],
  },
  {
    id: 'gobbi', name: 'Alfredo Gobbi', nickname: 'El violín romántico del tango',
    aliases: ['alfredo gobbi', 'gobbi'], artistAliases: [], nicknames: [],
    active: [1942, 1960], color: '#7b2cbf',
    summary: 'Sophisticated and expressive, with a link between Troilo and Pugliese: rhythmic depth and lyrical violin.',
    listenFor: ['A romantic solo violin.', 'Complex arrangements with strong rhythmic marcato.'],
    eras: [{ years: '1940s–50s', note: 'Jorge Maciel among others.' }],
    singers: ['Jorge Maciel'],
    confusable: ['pugliese', 'troilo'],
    vs: {},
    tracks: [],
  },
  {
    id: 'francini', name: 'Francini–Pontier', nickname: '',
    aliases: ['francini pontier', 'pontier francini', 'francini armando pontier', 'francini y pontier'], artistAliases: [], nicknames: [],
    active: [1945, 1955], color: '#5e548e',
    summary: 'A modern 1940s–50s orchestra from two former Caló musicians, with rich, flowing arrangements.',
    listenFor: ['A modern, rich sound with a smooth flow.', 'Strong vocalists (Julio Sosa, Alberto Podestá).'],
    eras: [{ years: '1945–1955', note: 'Julio Sosa, Alberto Podestá, Roberto Rufino.' }],
    singers: ['Julio Sosa', 'Alberto Podestá', 'Roberto Rufino'],
    confusable: ['calo', 'troilo'],
    vs: {},
    tracks: [],
  },
];

// Ensembles and leaders that share a name with an orchestra above but are not that orchestra.
// Tracks by these stay unrecognised (assign them by hand in the Library tab if you want them).
export const SEPARATE_ENSEMBLES = [
  'troilo grela', 'hermanos calo',
  'juan canaro', 'rafael canaro', 'mario canaro', 'francisco de caro',
  'leopoldo federico', 'donato racciatti',
];

// Extra aliases for detecting singers by surname alone (only for distinctive surnames).
export const SINGER_SURNAMES = {
  'Walter Cabral': ['cabral'], 'Enrique Carbel': ['carbel'], 'Alberto Echagüe': ['echague'],
  'Héctor Mauré': ['maure'], 'Armando Laborde': ['laborde'], 'Roberto Rufino': ['rufino'],
  'Oscar Serpa': ['serpa'], 'Mario Pomar': ['pomar'], 'Roberto Florio': ['florio'],
  'Francisco Fiorentino': ['fiorentino'], 'Edmundo Rivero': ['rivero'], 'Roberto Goyeneche': ['goyeneche', 'polaco goyeneche'],
  'Roberto Chanel': ['chanel'], 'Alberto Morán': ['moran'], 'Jorge Maciel': ['maciel'], 'Alfredo Belusi': ['belusi'],
  'Raúl Berón': ['beron'], 'Raúl Iriarte': ['iriarte'], 'Alberto Castillo': ['castillo'],
  'Ángel Vargas': ['vargas'], 'Charlo': ['charlo'], 'Teófilo Ibáñez': ['ibanez'], 'Andrés Falgás': ['falgas'],
  'Hugo Duval': ['duval'], 'Carlos Dante': ['dante'], 'Julio Martel': ['martel'], 'Oscar Larroca': ['larroca'],
  'Rodolfo Lesica': ['lesica'], 'Romeo Gavio': ['gavio'], 'Argentino Ledesma': ['ledesma'],
};

export const ERAS = [
  { id: 'pre35', label: 'Before 1935', from: 0, to: 1934 },
  { id: '35-39', label: '1935–1939', from: 1935, to: 1939 },
  { id: '40-44', label: '1940–1944', from: 1940, to: 1944 },
  { id: '45-49', label: '1945–1949', from: 1945, to: 1949 },
  { id: '50s', label: '1950s', from: 1950, to: 1959 },
  { id: '60+', label: '1960 and later', from: 1960, to: 9999 },
];

export const eraOf = year => (year ? ERAS.find(e => year >= e.from && year <= e.to) : null);
export const orchById = Object.fromEntries(ORCHESTRAS.map(o => [o.id, o]));
